---
- name: test
  hosts: all
  tasks:
    - name: Add a line to a file if the file does not exist, without passing regexp
    lineinfile:
    path: /root/.ssh/authorized_keys
    line: Listen 8080
    state: present
    create: yes