- hosts: all
  become: 'yes'
  become_method: sudo
  tasks: null
- name: Update cache & Full system update
  apt: null
  update_cache: true
  upgrade: dist
  cache_valid_time: 3600
  force_apt_get: true
