--- 
- hosts: all
  tasks:

  # Podemos adicionar "*.txt" | "heloworld.txt" | "*"(este apaga todos os arquivos ) etc...
  - name: Ansible delete all  file glob
  - find:
      paths: /tmp/  
      patterns: "*.web"
    register: find_results

  - file:
      path: "{{ item['path'] }}"
      state: absent
    with_items: "{{ find_results['files'] }}"
  - name: Add temp marker
    copy:
      content: '### AFTER THIS LINE'
      dest: /tmp/heloworld.txt  
    lineinfile:
      path: /tmp/heloworld.txt
      insertafter: '### AFTER THIS LINE'
      line: "###TEMP MARKER###"
      state: present
  - name: Add content
    lineinfile:
      path: /tmp/heloworld.txt
      insertbefore: '###TEMP MARKER###'
      line: "{{ item }}"
    with_items:
      - '# This is line 1'
      - '# This is line 2'
      - '# This is line 3'
  #- name: Remove temp marker
   # lineinfile:
  #    path: /tmp/heloworld.txt
   #   line: "###TEMP MARKER###"
  #    state: absent