--- 
- hosts: all
  tasks:

  - name: call the slave playbook delete-multiple-files-.txt.yml
    include_tasks: delete-multiple-files-.txt.yml

  - name: call the slave create-file-heloworld.yml
    include_tasks: create-file-heloworld.yml
    copy:
        content: '### AFTER THIS LINE'
        dest: /tmp/heloworld.txt  
    lineinfile:
      path: /tmp/heloworld.txt
      insertafter: '### AFTER THIS LINE'
      line: "###TEMP MARKER###"
      state: present
  - name: Create a file called '/tmp/heloworld.txt' with the content 'hello world'.
    copy:
        content: hello world
        dest: /tmp/heloworld.txt
  - name: Add content
    lineinfile:
      path: /tmp/heloworld.txt
      insertbefore: '###TEMP MARKER###'
      line: "{{ item }}"
    with_items:
      - '# This is line 1'
      - '# This is line 2'
      - '# This is line 3'
  #- name: Remove temp marker
   # lineinfile:
  #    path: /tmp/heloworld.txt
   #   line: "###TEMP MARKER###"
  #    state: absent