--- 
- hosts: all
  gather_facts: no
  become: no
  tasks:
    - name: generate 100 empty files
      file:
        path: "/tmp/playing_opera/loopdemo/file{{ item }}"
        state: touch
      with_sequence: start=1 end=100