---
- name: This is a hello-world example
  hosts: all
  tasks:
    - name: Create a file called '/tmp/heloworld.txt' with the content 'hello world'.
      copy:
        content: hello world
        dest: /tmp/heloworld.txt