---
- name: test
- hosts: all
  tasks:
  - name: Ansible delete file glob
    find:
      paths: /tmp
      patterns: "*.txt"
    register: files_to_delete

  - name: Ansible remove file glob
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_to_delete.files }}"